dependencies:
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: jenkins-prometheus-exporter
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: node-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
